import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Wallet,Plus,Settings,Trash2,Edit3,Download,Upload,ChevronLeft,ChevronRight,TrendingUp,CalendarDays,BarChart3,X,Check,Search,Save,ArrowUpRight,ArrowDownRight} from 'lucide-react';
import './styles.css';

const KEY='expenseflow-v1';
const defaultSettings={currency:'₹',monthStart:1,categories:['Food','Transport','Shopping','Bills','Health','Education','Entertainment','Other'],columns:[
 {id:'date',label:'Date',type:'date',required:true}, {id:'description',label:'Description',type:'text',required:true}, {id:'category',label:'Category',type:'category',required:true}, {id:'amount',label:'Amount',type:'number',required:true}, {id:'payment',label:'Payment Method',type:'text',required:false}
]};
const seed={settings:defaultSettings,expenses:[]};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||seed}catch{return seed}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
const money=(n,c='₹')=>`${c}${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const ym=(d)=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
const monthLabel=(s)=>new Date(Number(s.slice(0,4)),Number(s.slice(5))-1,1).toLocaleDateString('en-IN',{month:'long',year:'numeric'});
const currentYM=()=>ym(new Date());
function App(){
 const [data,setData]=useState(load()); const [month,setMonth]=useState(currentYM()); const [tab,setTab]=useState('dashboard'); const [modal,setModal]=useState(null); const [editing,setEditing]=useState(null); const [query,setQuery]=useState('');
 const update=(fn)=>setData(d=>{const n=fn(structuredClone(d));save(n);return n});
 const monthExpenses=useMemo(()=>data.expenses.filter(e=>ym(e.date)===month),[data.expenses,month]);
 const total=monthExpenses.reduce((a,e)=>a+Number(e.amount||0),0);
 const prevYM=useMemo(()=>{const [y,m]=month.split('-').map(Number);return ym(new Date(y,m-2,1))},[month]);
 const prevTotal=data.expenses.filter(e=>ym(e.date)===prevYM).reduce((a,e)=>a+Number(e.amount||0),0);
 const quarter=useMemo(()=>{const [y,m]=month.split('-').map(Number);const start=Math.floor((m-1)/3)*3; const ms=[0,1,2].map(i=>ym(new Date(y,start+i,1)));return {months:ms,total:ms.reduce((s,x)=>s+data.expenses.filter(e=>ym(e.date)===x).reduce((a,z)=>a+Number(z.amount||0),0),0)}} ,[month,data.expenses]);
 const quarterlyEstimate=quarter.total/Math.max(1,quarter.months.filter(x=>data.expenses.some(e=>ym(e.date)===x)).length)*3;
 const allMonths=[...new Set(data.expenses.map(e=>ym(e.date)))].sort().reverse(); if(!allMonths.includes(month)) allMonths.unshift(month);
 const filtered=monthExpenses.filter(e=>Object.values(e).some(v=>String(v).toLowerCase().includes(query.toLowerCase())));
 const addExpense=(payload)=>{update(d=>{d.expenses.unshift({...payload,id:crypto.randomUUID()});return d});setModal(null)};
 const editExpense=(payload)=>{update(d=>{const i=d.expenses.findIndex(x=>x.id===payload.id);d.expenses[i]=payload;return d});setEditing(null)};
 const remove=(id)=>update(d=>{d.expenses=d.expenses.filter(e=>e.id!==id);return d});
 const changeMonth=(dir)=>{const [y,m]=month.split('-').map(Number);setMonth(ym(new Date(y,m-1+dir,1)))};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><div className="brandIcon"><Wallet size={20}/></div><span>Expense<span className="accent">Flow</span></span></div>
   <nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}><BarChart3/>Dashboard</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}><CalendarDays/>Expenses</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><TrendingUp/>History</button></nav>
   <div className="sideBottom"><button onClick={()=>setModal('settings')}><Settings/>Settings</button><div className="storage"><span className="dot"></span><div><b>Local storage</b><small>Your data stays on this device</small></div></div></div>
  </aside>
  <main><header><div><p className="eyebrow">PERSONAL FINANCE</p><h1>{tab==='dashboard'?'Good money habits start here.':tab==='expenses'?'Expense ledger':'Spending history'}</h1></div><button className="primary" onClick={()=>setModal('add')}><Plus size={18}/> Add expense</button></header>
   <div className="monthbar"><button onClick={()=>changeMonth(-1)}><ChevronLeft/></button><div><b>{monthLabel(month)}</b><span>{monthExpenses.length} transactions</span></div><button onClick={()=>changeMonth(1)}><ChevronRight/></button><button className="today" onClick={()=>setMonth(currentYM())}>This month</button></div>
   {tab==='dashboard'&&<Dashboard total={total} prevTotal={prevTotal} quarter={quarter} estimate={quarterlyEstimate} currency={data.settings.currency} expenses={monthExpenses} settings={data.settings} onAdd={()=>setModal('add')} />}
   {tab==='expenses'&&<Ledger expenses={filtered} settings={data.settings} query={query} setQuery={setQuery} onAdd={()=>setModal('add')} onEdit={setEditing} onDelete={remove}/>} 
   {tab==='history'&&<History expenses={data.expenses} currency={data.settings.currency} month={month} setMonth={setMonth}/>} 
  </main>
  {modal==='add'&&<ExpenseModal settings={data.settings} onClose={()=>setModal(null)} onSave={addExpense}/>} {editing&&<ExpenseModal settings={data.settings} initial={editing} onClose={()=>setEditing(null)} onSave={editExpense}/>} {modal==='settings'&&<SettingsModal settings={data.settings} onClose={()=>setModal(null)} onSave={s=>{update(d=>{d.settings=s;return d});setModal(null)}}/>}
 </div>
}
function Dashboard({total,prevTotal,quarter,estimate,currency,expenses,settings,onAdd}){const delta=prevTotal?((total-prevTotal)/prevTotal)*100:0; const cats=settings.categories.map(c=>({c,v:expenses.filter(e=>e.category===c).reduce((a,e)=>a+Number(e.amount||0),0)})).filter(x=>x.v).sort((a,b)=>b.v-a.v); const max=cats[0]?.v||1; return <section>
 <div className="cards"><Card title="Spent this month" value={money(total,currency)} sub={prevTotal?`${delta>=0?'+':''}${delta.toFixed(1)}% vs last month`: 'No previous month data'} trend={delta}/><Card title="3-month actual" value={money(quarter.total,currency)} sub={`${quarter.months.filter(m=>expenses.length||true).length} month window`}/><Card title="3-month estimate" value={money(estimate,currency)} sub="Based on recorded months"/></div>
 <div className="grid2"><div className="panel"><div className="panelHead"><div><h2>Category breakdown</h2><p>Where your money went this month</p></div><button className="iconBtn" onClick={onAdd}><Plus/></button></div>{cats.length?<div className="bars">{cats.map(x=><div className="barRow" key={x.c}><div><span>{x.c}</span><b>{money(x.v,currency)}</b></div><div className="bar"><i style={{width:`${(x.v/max)*100}%`}}/></div></div>)}</div>:<Empty text="No expenses yet"/>}</div>
 <div className="panel"><div className="panelHead"><div><h2>Recent transactions</h2><p>Latest activity in this month</p></div></div>{expenses.length?<div className="miniList">{expenses.slice(0,6).map(e=><div className="mini" key={e.id}><div className="miniIcon">{e.category?.[0]||'₹'}</div><div><b>{e.description||'Expense'}</b><small>{e.category} · {e.date}</small></div><strong>{money(e.amount,currency)}</strong></div>)}</div>:<Empty text="Add your first expense to see it here"/>}</div></div>
 <div className="tip"><ArrowUpRight/><div><b>Quarterly planning</b><span>Your estimate recalculates automatically from the months you record. Older months remain saved.</span></div></div>
 </section>}
function Card({title,value,sub,trend}){return <div className="card"><span>{title}</span><strong>{value}</strong><small className={trend>0?'bad':trend<0?'good':''}>{trend!=null&&trend!==0?(trend>0?'↑':'↓')+' ':''}{sub}</small></div>}
function Ledger({expenses,settings,query,setQuery,onAdd,onEdit,onDelete}){return <section><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search expenses..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary" onClick={onAdd}><Plus/> Add expense</button></div><div className="tableWrap"><table><thead><tr>{settings.columns.map(c=><th key={c.id}>{c.label}</th>)}<th></th></tr></thead><tbody>{expenses.length?expenses.map(e=><tr key={e.id}>{settings.columns.map(c=><td key={c.id}>{c.id==='amount'?<b>{money(e[c.id],settings.currency)}</b>:c.id==='category'?<span className="tag">{e[c.id]}</span>:e[c.id]}</td>)}<td className="actions"><button onClick={()=>onEdit(e)}><Edit3/></button><button onClick={()=>onDelete(e.id)}><Trash2/></button></td></tr>):<tr><td colSpan={settings.columns.length+1}><Empty text="No matching expenses"/></td></tr>}</tbody></table></div></section>}
function History({expenses,currency,month,setMonth}){const months=[...new Set(expenses.map(e=>ym(e.date)))].sort().reverse(); return <section><div className="historyHero"><TrendingUp size={24}/><div><b>Every month is saved</b><span>Browse your full spending timeline. Nothing is overwritten when you change months.</span></div></div><div className="monthGrid">{months.length?months.map(m=>{const total=expenses.filter(e=>ym(e.date)===m).reduce((a,e)=>a+Number(e.amount||0),0);return <button key={m} onClick={()=>{setMonth(m)}} className={m===month?'selected':''}><span>{monthLabel(m)}</span><strong>{money(total,currency)}</strong><small>{expenses.filter(e=>ym(e.date)===m).length} transactions</small></button>}):<Empty text="Your past months will appear here"/>}</div></section>}
function Empty({text}){return <div className="empty">{text}</div>}
function ExpenseModal({settings,initial,onClose,onSave}){const [form,setForm]=useState(initial||Object.fromEntries(settings.columns.map(c=>[c.id,c.id==='date'?new Date().toISOString().slice(0,10):'']))); const set=(k,v)=>setForm(f=>({...f,[k]:v})); const submit=e=>{e.preventDefault(); if(settings.columns.filter(c=>c.required).some(c=>!form[c.id]))return;onSave(form)}; return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modalHead"><div><p className="eyebrow">{initial?'EDIT':'NEW'} TRANSACTION</p><h2>{initial?'Edit expense':'Add expense'}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="formGrid">{settings.columns.map(c=><label key={c.id}>{c.label}{c.required?' *':''}{c.type==='category'?<select value={form[c.id]||''} onChange={e=>set(c.id,e.target.value)}><option value="">Select category</option>{settings.categories.map(x=><option key={x}>{x}</option>)}</select>:<input type={c.type==='number'?'number':c.type==='date'?'date':'text'} step={c.type==='number'?'0.01':undefined} value={form[c.id]||''} onChange={e=>set(c.id,e.target.value)}/>}</label>)}</div><div className="modalActions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Save size={17}/>{initial?'Save changes':'Save expense'}</button></div></form></div>}
function SettingsModal({settings,onClose,onSave}){const [s,setS]=useState(structuredClone(settings));const [newCat,setNewCat]=useState(''); const addCat=()=>{if(newCat.trim()&&!s.categories.includes(newCat.trim()))setS(x=>({...x,categories:[...x.categories,newCat.trim()]}));setNewCat('')}; const addCol=()=>setS(x=>({...x,columns:[...x.columns,{id:'custom_'+Date.now(),label:'New column',type:'text',required:false}]})); const upd=(id,k,v)=>setS(x=>({...x,columns:x.columns.map(c=>c.id===id?{...c,[k]:v}:c)})); const del=id=>setS(x=>({...x,columns:x.columns.filter(c=>c.id!==id)})); return <div className="overlay"><div className="modal wide"><div className="modalHead"><div><p className="eyebrow">CONFIGURATION</p><h2>Settings</h2></div><button onClick={onClose}><X/></button></div><div className="settingsScroll"><div className="settingBlock"><h3>Currency</h3><input value={s.currency} maxLength="4" onChange={e=>setS({...s,currency:e.target.value})}/></div><div className="settingBlock"><h3>Expense columns</h3><p className="hint">Every column is configurable. Rename it, change its input type, or remove it.</p>{s.columns.map(c=><div className="columnRow" key={c.id}><input value={c.label} onChange={e=>upd(c.id,'label',e.target.value)}/><select value={c.type} onChange={e=>upd(c.id,'type',e.target.value)}><option value="text">Text</option><option value="date">Date</option><option value="number">Number</option><option value="category">Category</option></select><label className="check"><input type="checkbox" checked={c.required} onChange={e=>upd(c.id,'required',e.target.checked)}/> Required</label><button onClick={()=>del(c.id)} disabled={s.columns.length<=1}><Trash2/></button></div>)}<button className="secondary" onClick={addCol}><Plus/> Add column</button></div><div className="settingBlock"><h3>Categories</h3><div className="chips">{s.categories.map(c=><span key={c}>{c}<button onClick={()=>setS(x=>({...x,categories:x.categories.filter(y=>y!==c)}))}><X size={12}/></button></span>)}</div><div className="catAdd"><input placeholder="New category" value={newCat} onChange={e=>setNewCat(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addCat()}/><button className="secondary" onClick={addCat}>Add</button></div></div></div><div className="modalActions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}><Check size={17}/>Save settings</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
